package com.mengya.dianping.dal;

import com.mengya.dianping.model.RecommendModel;

public interface RecommendModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    int insert(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    int insertSelective(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    RecommendModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    int updateByPrimaryKeySelective(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sat May 08 17:14:39 CST 2021
     */
    int updateByPrimaryKey(RecommendModel record);
}